services:
    # this is only a parent service definition for the child services below
    zikula_oauth_module.authentication_method.base:
        abstract: true
        arguments:
          - '@session'
          - '@request_stack'
          - '@router'
          - '@zikula_oauth_module.mapping_repository'
          - '@zikula_extensions_module.api.variable'

    zikula_oauth_module.authentication_method.github:
        parent: zikula_oauth_module.authentication_method.base
        class: Zikula\OAuthModule\AuthenticationMethod\GithubAuthenticationMethod
        tags:
            - { name: zikula.authentication_method, alias: 'github' }
            # the alias should be a class constant in Symfony >=3.2 !php/const:Zikula\OAuthModule\OAuthConstant::ALIAS_GITHUB

    zikula_oauth_module.authentication_method.google:
        parent: zikula_oauth_module.authentication_method.base
        class: Zikula\OAuthModule\AuthenticationMethod\GoogleAuthenticationMethod
        tags:
            - { name: zikula.authentication_method, alias: 'google' }
            # the alias should be a class constant in Symfony >=3.2 !php/const:Zikula\OAuthModule\OAuthConstant::ALIAS_GOOGLE

    zikula_oauth_module.authentication_method.facebook:
        parent: zikula_oauth_module.authentication_method.base
        class: Zikula\OAuthModule\AuthenticationMethod\FacebookAuthenticationMethod
        tags:
            - { name: zikula.authentication_method, alias: 'facebook' }
            # the alias should be a class constant in Symfony >=3.2 !php/const:Zikula\OAuthModule\OAuthConstant::ALIAS_FACEBOOK

    zikula_oauth_module.authentication_method.linkedin:
        parent: zikula_oauth_module.authentication_method.base
        class: Zikula\OAuthModule\AuthenticationMethod\LinkedInAuthenticationMethod
        tags:
            - { name: zikula.authentication_method, alias: 'linkedin' }
            # the alias should be a class constant in Symfony >=3.2 !php/const:Zikula\OAuthModule\OAuthConstant::ALIAS_LINKEDIN
