services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $bundle: '@Zikula\OAuthModule\ZikulaOAuthModule'

    Zikula\OAuthModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'
